language: node_js

node_js:
  - "node"

sudo: false

branches:
  except:
    - gh-pages

script:
  - npm run cover

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js